# Generated by Django 2.1.3 on 2018-12-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181122_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.CourseName'),
        ),
        migrations.AlterField(
            model_name='review',
            name='professor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Professor'),
        ),
    ]
