# Generated by Django 2.1.3 on 2018-11-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181122_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='course_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
